# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Funkstr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Funkstr
  #pod 'XMPPFramework', :git=> 'git@github.com:robbiehanson/XMPPFramework.git', :branch=>'master'
  pod 'XMPPFramework/Swift'
  pod 'RealmSwift'
  pod 'NoChat', '~> 0.3'
  # pod 'Chatto', '= 3.3.1'
  # pod 'ChattoAdditions', '= 3.3.1' # if you want to use the cells or the input component
  pod 'YYText'
  pod 'HPGrowingTextView'
  pod 'XMLKit'
end
